# Generated by Django 5.2.1 on 2025-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_monthly',
            field=models.BooleanField(default=True, help_text='Automatically renew every month'),
        ),
    ]
