# Generated by Django 5.2.1 on 2025-09-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_category_is_monthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when payment was made', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
    ]
