# Generated by Django 5.2.1 on 2025-10-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
