# Generated by Django 5.2.1 on 2025-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_delete_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.CharField(blank=True, help_text='Category ID for identification', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='gcash_number',
            field=models.CharField(blank=True, help_text='GCash account number for payments', max_length=15),
        ),
    ]
