# Generated by Django 5.2.1 on 2025-11-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_budgethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('partial', 'Partial Payment')], default='full', max_length=10),
        ),
    ]
